  version: '3.8'

  services:
    gatekeeper-proxy:
      image: gatekeeper-proxy
      build:
        context: .
        dockerfile: Dockerfile
      environment:
          PROXY_TARGET_URL: '["http://my.domain.or.address1", "https://my.domain.or.address2"]'
          # LOAD_BALANCE_MODE: round-robin
          DB_TYPE: mariadb
          DB_HOST: mariaDbHost
          DB_PORT: 3306
          DB_NAME: gatekeeper
          DB_USERNAME: myUser
          DB_PASSWORD: myUserPass
          TABLE_NAME: api_tokens
          COLUMN_NAME: user_tokens
          # RATE_LIMIT_ENABLED: "true"
          # RATE_LIMIT_RATE: 100
          # RATE_LIMIT_TIMEOUT: 60
          # RATE_LIMIT_MODE: global
          # ENABLE_CACHING: "true"
          # CACHE_MAX_SIZE: 100
          # CACHE_MAX_DURATION_M: 10
      #volumes:
      #    - type: bind
      #      source: /your/host/path/here/logs
      #      target: /var/log/gatekeeper
      ports:
        - "8080:8080"

